### ISSUE TITLE
Option to disable italic font style

### ISSUE THREAD

**Issue by volsa** [ptkdev/vscode-theme-dark-blood#1]
Currently there's no way to disable the italic font style (at least I wasn't able to find such an option) and while it is possible to do so via some VSCode shenanigans as seen [here](https://github.com/microsoft/vscode/issues/32579#issuecomment-341502559) it would be much more cleaner if there was an official option (i.e. `"darkblood.disableItalics": true`). Is there any way you could implement it?

**Comment by ptkdev** [comment]
Thanks! 
I try add this feature in next release.

**Comment by ptkdev** [comment]
Available in [v3.0.0](https://marketplace.visualstudio.com/items?itemName=ptkdev.dark-blood-theme)
